const D=window.HUB_DATA;
// Audio is isolated here so an Oxford audio provider/API can be plugged in later without changing the UI.
const AUDIO_CONFIG={provider:'browser-en-GB',oxfordAudioBaseUrl:''};
const $=s=>document.querySelector(s);const app=$('#app');
const state={grade:Number(localStorage.getItem('hubGrade')||1),page:localStorage.getItem('hubPage')||'overview',vocabTab:'today',storyId:Number(localStorage.getItem('hubStory')||1),storyGrade:Number(localStorage.getItem('hubStoryGrade')||1),gameScore:0,gameIndex:0};
const progress=JSON.parse(localStorage.getItem('hubProgress')||'{}');
function save(){localStorage.setItem('hubProgress',JSON.stringify(progress));localStorage.setItem('hubGrade',state.grade);localStorage.setItem('hubPage',state.page);localStorage.setItem('hubStory',state.storyId);localStorage.setItem('hubStoryGrade',state.storyGrade);updatePill();}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function speak(text,lang='en-GB'){if(!('speechSynthesis'in window)){toast('Thiết bị chưa hỗ trợ đọc âm thanh');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=0.82;const voices=speechSynthesis.getVoices();const v=voices.find(x=>x.lang===lang)||voices.find(x=>x.lang.startsWith(lang.split('-')[0]));if(v)u.voice=v;speechSynthesis.speak(u)}
function updatePill(){const p=progress.today||{};const total=10;const done=Object.values(p).filter(Boolean).length;$('#progressPill').textContent=`${Math.round(done/total*100)}% hôm nay`}
function renderNav(){let h='<button class="grade '+(state.page==='overview'?'active':'')+'" data-page="overview">🏠 <span>Tổng quan</span><span class="arrow">›</span></button>';for(let g=1;g<=10;g++){h+=`<button class="grade ${state.grade===g?'active':''}" data-grade="${g}">📁 <span>Lớp ${g}</span><span class="arrow">›</span></button>`;if(state.grade===g)h+=`<div class="subnav"><button data-page="vocabGames" class="${state.page==='vocabGames'?'active':''}">🌈 Vocabulary Games</button><button data-page="vocabList" class="${state.page==='vocabList'?'active':''}">📚 Vocabulary List</button><button data-page="math" class="${state.page==='math'?'active':''}">➗ Toán tư duy</button><button data-page="vietnamese" class="${state.page==='vietnamese'?'active':''}">📖 Tiếng Việt</button></div>`}$('#gradeNav').innerHTML=h;document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{state.grade=+b.dataset.grade;state.page='vocabGames';save();render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;save();render()})}
function render(){renderNav();$('#pageTitle').textContent=state.page==='overview'?'Tổng quan':state.page==='vocabGames'?'Vocabulary Games':state.page==='vocabList'?'Vocabulary List':state.page==='math'?'Toán tư duy':'Tiếng Việt';({overview:renderOverview,vocabGames:renderGames,vocabList:renderVocab,math:renderMath,vietnamese:renderVietnamese}[state.page]||renderOverview)();updatePill()}
function renderOverview(){app.innerHTML=`<div class="hero"><div><div class="eyebrow" style="color:#eee">CHÀO MỪNG BẠN NHỎ</div><h2>Học vui • Nhớ lâu • Tự tin</h2><p>Lớp ${state.grade} · Chọn một khu vực để bắt đầu hôm nay.</p></div><div class="hero-art">🧒📚</div></div><div class="stats"><div class="stat"><strong>10</strong><span>Từ mới hôm nay</span></div><div class="stat"><strong>${D.stories.filter(x=>x.grade===state.grade).length}</strong><span>Truyện lớp ${state.grade}</span></div><div class="stat"><strong>50</strong><span>Trang Toán từ PDF</span></div></div><h2 class="section-title">Nội dung học</h2><div class="grid"><div class="card module-card" data-go="vocabGames"><div class="module-icon">🌈</div><h3>Vocabulary Games</h3><p>Hoàn thiện từ, chọn từ đúng và nghe phát âm tiếng Anh.</p><span class="go">Học ngay →</span></div><div class="card module-card" data-go="vocabList"><div class="module-icon">📚</div><h3>Vocabulary List</h3><p>10 từ mới hôm nay, flashcard, đã thuộc và cần học.</p><span class="go">Mở danh sách →</span></div><div class="card module-card" data-go="math"><div class="module-icon">🧠</div><h3>Toán tư duy</h3><p>Toàn bộ nội dung quyển Toán lớp 1 Quyển 1 trong PDF đã đính kèm.</p><span class="go">Làm bài →</span></div><div class="card module-card" data-go="vietnamese"><div class="module-icon">📖</div><h3>Tiếng Việt</h3><p>100 câu chuyện ngắn theo lớp, đọc to và trả lời trắc nghiệm.</p><span class="go">Đọc truyện →</span></div></div>`;document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{state.page=x.dataset.go;save();render()})}
function vocab(){return D.vocabulary[String(state.grade)]||[]}
function isMastered(word){return !!(progress.mastered&&progress.mastered[word])}
function setMastered(word,val){progress.mastered=progress.mastered||{};progress.mastered[word]=val;progress.today=progress.today||{};progress.today[word]=val;save()}
function renderVocab(){const words=vocab();const mastered=words.filter(x=>isMastered(x.word));const need=words.filter(x=>!isMastered(x.word));let body='';if(state.vocabTab==='today'){body=`<div class="flash-grid">${words.map((x,i)=>`<div class="flash"><div><span class="eyebrow">TỪ ${i+1}/10</span><div class="word">${x.word}</div><div class="meaning">${x.meaning}</div></div><div class="flash-actions"><button class="btn secondary sound" title="Nghe phát âm" data-speak="${x.word}">🔊</button><button class="btn ${isMastered(x.word)?'good':'warn'}" data-master="${x.word}">${isMastered(x.word)?'✓ Đã thuộc':'□ Cần học'}</button></div></div>`).join('')}</div>`}else{const arr=state.vocabTab==='mastered'?mastered:need;body=arr.length?`<div class="word-list">${arr.map(x=>`<div class="word-row"><b>${x.word}</b><span>${x.meaning}</span><button class="btn secondary sound" data-speak="${x.word}">🔊</button><label class="check"><input type="checkbox" ${isMastered(x.word)?'checked':''} data-check="${x.word}"> Đã thuộc</label></div>`).join('')}</div>`:`<div class="empty">Chưa có từ nào ở mục này.</div>`}
app.innerHTML=`<div class="toolbar"><select id="gradeSelect" class="select">${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${state.grade===i+1?'selected':''}>Lớp ${i+1}</option>`).join('')}</select><span class="muted">10 từ được phân bổ theo lớp. Phát âm dùng giọng English (UK); có thể thay provider bằng Oxford API sau.</span></div><div class="tabs"><button class="tab ${state.vocabTab==='today'?'active':''}" data-vtab="today">10 từ mới hôm nay</button><button class="tab ${state.vocabTab==='mastered'?'active':''}" data-vtab="mastered">Vocab đã thuộc (${mastered.length})</button><button class="tab ${state.vocabTab==='need'?'active':''}" data-vtab="need">Cần học (${need.length})</button></div>${body}`;
$('#gradeSelect').onchange=e=>{state.grade=+e.target.value;save();render()};document.querySelectorAll('[data-vtab]').forEach(x=>x.onclick=()=>{state.vocabTab=x.dataset.vtab;render()});document.querySelectorAll('[data-speak]').forEach(x=>x.onclick=()=>speak(x.dataset.speak));document.querySelectorAll('[data-master]').forEach(x=>x.onclick=()=>{setMastered(x.dataset.master,!isMastered(x.dataset.master));render()});document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{setMastered(x.dataset.check,x.checked);render()})}
let gameWords=[];function resetGame(){gameWords=vocab();state.gameIndex=0;state.gameScore=0}
function renderGames(){if(!gameWords.length)resetGame();const w=gameWords[state.gameIndex%gameWords.length];const next=(state.gameIndex+1)%gameWords.length;const choices=[w.word,...vocab().filter(x=>x.word!==w.word).slice(0,3).map(x=>x.word)].sort(()=>Math.random()-.5);const masked=w.word.length>4?w.word[0]+' _ '.repeat(Math.max(1,Math.min(3,w.word.length-2)))+w.word[w.word.length-1]:w.word[0]+' _ '+w.word.slice(2);app.innerHTML=`<div class="note">🎧 Nút 🔊 phát âm bằng giọng English (UK) của trình duyệt. Kiến trúc đã tách riêng để tích hợp Oxford audio/API khi bạn cung cấp key/provider.</div><div class="game-grid"><div class="card game-card"><div class="eyebrow">GAME 1 · CHỌN TỪ</div><div class="game-question">Từ tiếng Anh nào có nghĩa <em>“${w.meaning}”</em>?</div><div class="options">${choices.map(c=>`<button class="option" data-choice="${c}">${c}</button>`).join('')}</div><div class="muted" style="margin-top:16px">Điểm: <b>${state.gameScore}</b> · ${state.gameIndex+1}/${gameWords.length}</div></div><div class="card game-card"><div class="eyebrow">GAME 2 · HOÀN THIỆN TỪ</div><div class="game-question">${masked}</div><button class="btn secondary sound" data-speak="${w.word}" style="margin-bottom:12px">🔊 Nghe</button><input id="fillInput" class="input" placeholder="Gõ từ hoàn chỉnh…" autocomplete="off"><button id="checkFill" class="btn primary" style="margin-top:10px;width:100%">Kiểm tra</button><div id="fillResult" class="muted" style="margin-top:12px"></div></div></div>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(b.dataset.choice===w.word){b.classList.add('correct');state.gameScore++;toast('Chính xác! 🎉');setTimeout(()=>{state.gameIndex=next;renderGames()},500)}else{b.classList.add('wrong');toast('Thử lại nhé!')}});$('#checkFill').onclick=()=>{const v=$('#fillInput').value.trim().toLowerCase();if(v===w.word){$('#fillResult').textContent='✓ Chính xác!';state.gameScore++;setTimeout(()=>{state.gameIndex=next;renderGames()},500)}else $('#fillResult').textContent='Chưa đúng — nghe lại và thử lần nữa.'};document.querySelector('[data-speak]').onclick=()=>speak(w.word)}
function renderMath(){app.innerHTML=`<div class="note">📘 Nội dung Toán được giữ nguyên theo file PDF bạn đã đính kèm: <b>Toán lớp 1 — Quyển 1</b>. PDF được nhúng trực tiếp vào ứng dụng để giữ nguyên nội dung bài tập.</div><div class="math-viewer"><div class="math-toolbar"><button class="btn secondary" onclick="document.getElementById('pdfFrame').contentWindow.print()">🖨 In</button><a class="btn primary" href="assets/toan-lop1-quyen1.pdf" target="_blank">Mở PDF</a><span>50 trang · xem trên điện thoại hoặc máy tính</span></div><iframe id="pdfFrame" class="pdf" src="assets/toan-lop1-quyen1.pdf#page=1"></iframe></div>`}
function stories(){return D.stories.filter(s=>s.grade===state.storyGrade)}
function renderVietnamese(){let list=stories();if(!list.find(s=>s.id===state.storyId))state.storyId=list[0].id;const s=list.find(x=>x.id===state.storyId);app.innerHTML=`<div class="toolbar"><select id="storyGrade" class="select">${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${state.storyGrade===i+1?'selected':''}>Lớp ${i+1}</option>`).join('')}</select><div class="read-controls"><button class="btn primary" id="readAll">🔊 Đọc to</button><button class="btn secondary" id="stopRead">⏹ Dừng</button></div><span class="muted">100 câu chuyện · mỗi truyện 8 câu · 3 câu hỏi trắc nghiệm</span></div><div class="reading-grid"><div class="card story-list">${list.map(x=>`<div class="story-item ${x.id===s.id?'active':''}" data-story="${x.id}"><b>${x.title}</b><small>8 câu · Lớp ${x.grade}</small></div>`).join('')}</div><div class="card"><div class="story-head"><div><div class="eyebrow">TIẾNG VIỆT · LỚP ${s.grade}</div><h2 class="story-title">${s.title}</h2></div><button class="btn secondary" id="readStory">🔊 Đọc truyện</button></div><div class="story-text">${s.sentences.map((t,i)=>`<span class="story-sentence">${i+1}. ${t}</span>`).join('')}</div><h3 class="section-title" style="margin-top:12px">Câu hỏi đọc hiểu</h3>${s.questions.map((q,qi)=>`<div class="question"><b>${qi+1}. ${q.q}</b><div class="options">${q.options.map((o,oi)=>`<button class="option" data-q="${qi}" data-a="${oi}">${o}</button>`).join('')}</div></div>`).join('')}</div></div>`;$('#storyGrade').onchange=e=>{state.storyGrade=+e.target.value;const l=stories();state.storyId=l[0].id;save();render()};document.querySelectorAll('[data-story]').forEach(x=>x.onclick=()=>{state.storyId=+x.dataset.story;save();render()});const read=()=>speak(s.sentences.join(' '),'vi-VN');$('#readStory').onclick=read;$('#readAll').onclick=read;$('#stopRead').onclick=()=>speechSynthesis.cancel();document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const qi=+b.dataset.q,ai=+b.dataset.a,correct=s.questions[qi].answer;document.querySelectorAll(`[data-q="${qi}"]`).forEach(x=>x.disabled=true);if(ai===correct){b.classList.add('correct');toast('Đúng rồi! ⭐')}else{b.classList.add('wrong');document.querySelector(`[data-q="${qi}"][data-a="${correct}"]`).classList.add('correct');toast('Xem lại câu trong bài nhé.')}})}
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');render();
