/* Curriculum vocabulary + word-family mind maps.
   Planning basis: Vietnam GDPT 2018 English: Primary (Grades 3-5) ~600-700 words;
   lower secondary adds ~800-1000 words; upper secondary adds ~600-800 words.
   Per-grade counts below are app planning targets, not official per-grade quotas. */
window.HUB_CURRICULUM={
  targets:{1:80,2:160,3:300,4:480,5:650,6:850,7:1080,8:1320,9:1550,10:1750},
  bands:{1:'Pre-A1/A1 nền tảng',2:'A1 nền tảng',3:'A1',4:'A1–A2',5:'A1–A2',6:'A2',7:'A2–B1',8:'A2–B1',9:'A2–B1',10:'B1–B2'},
  mindmaps:{
    1:[
      ['play','chơi',['player','playful','playground','playtime','playmate']],['school','trường học',['schoolbag','schoolwork','schoolyard','schoolmate','schoolhouse']],['friend','bạn',['friendly','friendship','befriend','unfriendly','best friend']],['home','nhà',['homeroom','homework','homeless','homemade','at home']],['help','giúp đỡ',['helper','helpful','helping','helpless','help out']],['happy','vui vẻ',['happily','happiness','unhappy','unhappily','happy family']],['read','đọc',['reader','reading','readable','reread','read aloud']],['kind','tốt bụng',['kindness','unkind','kindly','kind-hearted','kind person']]
    ],
    2:[
      ['work','làm việc',['worker','workplace','workbook','working','homework','teamwork']],['teach','dạy',['teacher','teaching','taught','teachable','teaching assistant']],['learn','học',['learner','learning','learned','learnable','learn by heart']],['care','quan tâm/chăm sóc',['careful','carefully','careless','caregiver','take care']],['clean','sạch/làm sạch',['cleaner','cleaning','unclean','cleanliness','clean up']],['cook','nấu ăn',['cooker','cooking','cookbook','cooked','home-cooked']],['move','di chuyển',['movement','mover','moving','remove','moveable']],['use','sử dụng',['useful','useless','user','reuse','useful tool']]
    ],
    3:[
      ['act','hành động',['action','active','activity','actor','actress','actively']],['talk','nói chuyện',['talker','talking','talkative','talk back','small talk']],['visit','thăm',['visitor','visiting','revisit','visitable','school visit']],['travel','du lịch',['traveller','travelling','traveling','travelled','travel plan']],['health','sức khỏe',['healthy','healthily','unhealthy','healthcare','health check']],['nature','thiên nhiên',['natural','naturally','unnatural','nature reserve','natural world']],['sport','thể thao',['sportsman','sporty','sporting','sportswear','team sport']],['weather','thời tiết',['weatherproof','weather report','weather forecast','rainy weather','bad weather']]
    ],
    4:[
      ['create','tạo ra',['creation','creative','creatively','creator','recreate','creativity']],['educate','giáo dục',['education','educational','educator','educated','educate yourself']],['communicate','giao tiếp',['communication','communicative','communicator','miscommunication','communicate clearly']],['organize','tổ chức',['organization','organized','organizer','reorganize','organizational']],['protect','bảo vệ',['protection','protective','protector','unprotected','environmental protection']],['decide','quyết định',['decision','decisive','indecision','decisively','decision-making']],['discover','khám phá',['discovery','discoverer','rediscover','discoverable','discovery trip']],['improve','cải thiện',['improvement','improved','improving','self-improvement','improve skills']]
    ],
    5:[
      ['develop','phát triển',['development','developer','developed','developing','developmental']],['environment','môi trường',['environmental','environmentally','environmentalist','eco-friendly','environment protection']],['experiment','thí nghiệm',['experimental','experimenter','experimentally','science experiment','experiment with']],['prepare','chuẩn bị',['preparation','prepared','preparatory','unprepared','prepare for']],['responsible','có trách nhiệm',['responsibility','responsibly','irresponsible','responsible for','social responsibility']],['communicate','giao tiếp',['communication','communicator','communicative','miscommunication','communication skills']],['achieve','đạt được',['achievement','achievable','achiever','achieving','high achievement']],['practice','luyện tập',['practical','practise','practiced','practicing','practice session']]
    ],
    6:[
      ['educate','giáo dục',['education','educational','educator','educated','educationally']],['inform','thông báo/cung cấp thông tin',['information','informative','informed','informant','misinform']],['connect','kết nối',['connection','connected','connective','disconnect','connectivity']],['decide','quyết định',['decision','decisive','indecisive','decisively','decision-making']],['different','khác biệt',['difference','differently','differentiate','differentiation','indifferent']],['possible','có thể',['possibility','possibly','impossible','impossibly','possibility of']],['communicate','giao tiếp',['communication','communicative','communicator','miscommunication','nonverbal communication']],['culture','văn hóa',['cultural','culturally','multicultural','culture shock','cultural identity']]
    ],
    7:[
      ['analyze','phân tích',['analysis','analytical','analyst','analytically','reanalyze']],['benefit','lợi ích',['beneficial','beneficiary','benefited','cost-benefit','benefit from']],['compare','so sánh',['comparison','comparative','comparatively','comparable','compare with']],['communicate','giao tiếp',['communication','communicative','communicator','miscommunication','communication gap']],['depend','phụ thuộc',['dependent','dependence','independent','independence','dependable']],['influence','ảnh hưởng',['influential','influenceable','influencer','self-influence','influence on']],['develop','phát triển',['development','developer','developed','developing','underdeveloped']],['require','yêu cầu',['requirement','required','requirement-based','requirement for','as required']]
    ],
    8:[
      ['construct','xây dựng',['construction','constructive','constructor','reconstruct','construction site']],['evaluate','đánh giá',['evaluation','evaluative','evaluator','reevaluate','self-evaluation']],['effective','hiệu quả',['effect','effectively','effectiveness','ineffective','cost-effective']],['rely','dựa vào',['reliable','reliability','unreliable','reliably','rely on']],['significant','quan trọng/đáng kể',['significance','significantly','insignificant','significant change','statistically significant']],['sustain','duy trì',['sustainable','sustainability','sustainably','unsustainable','sustainable development']],['innovate','đổi mới',['innovation','innovative','innovator','innovatively','technological innovation']],['interpret','diễn giải',['interpretation','interpreter','interpretive','misinterpret','reinterpret']]
    ],
    9:[
      ['communicate','giao tiếp',['communication','communicative','communicator','miscommunication','intercultural communication']],['influence','ảnh hưởng',['influential','influencer','influenced','counter-influence','influence strategy']],['research','nghiên cứu',['researcher','researching','research-based','researchable','research method']],['evidence','bằng chứng',['evident','evidently','evidence-based','supporting evidence','empirical evidence']],['justify','biện minh/chứng minh',['justification','justified','justifiable','unjustified','justify a claim']],['respond','phản hồi',['response','responsive','responsively','respondent','respond to']],['strategy','chiến lược',['strategic','strategically','strategist','strategy-based','learning strategy']],['perspective','góc nhìn',['perspectival','perspectives','cross-cultural perspective','different perspective','from a perspective']]
    ],
    10:[
      ['analyze','phân tích',['analysis','analytical','analyst','analytically','reanalyze','data analysis']],['signify','biểu thị/có ý nghĩa',['significant','significance','significantly','insignificant','signifier','signification']],['economy','kinh tế',['economic','economical','economically','economist','economics','socioeconomic']],['technology','công nghệ',['technological','technologist','technologically','biotechnology','technology-driven']],['environment','môi trường',['environmental','environmentalist','environmentally','eco-friendly','environmentalism']],['communicate','giao tiếp',['communication','communicative','communicator','miscommunication','intercultural communication']],['create','tạo ra',['creation','creative','creator','creativity','recreate','creative thinking']],['achieve','đạt được',['achievement','achievable','achiever','high-achieving','achievement-oriented']]
    ]
  }
};
